services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "django-insecure-!(t-!f#6g#sr%yfded9(xha)g+=!6craeez^cp+*&bz_7vdk61"
      GHUSER: "irondes"
      GHBEARER: ""
      GENURL: "acesso.irondes.com.br"
      PROTOCOL: "https"
      REPONAME: "rdgen"
    ports:
      - "8001:8000"
    dns:
      - 8.8.8.8
